### ISSUE TITLE
Deterministic input recording/playback

### ISSUE THREAD

**Issue by OvertureGames** [jkuhlmann/gainput#12]
Hey, really liking the library.

I noticed you use a time stamp for recording and playing back input events. While this works for the most part, I don't believe it can achieve true deterministic reliability (for replaying a session). The framework using your library would have to update its state/input at a fixed frequency, which would replace time stamps with a simple integer counter.

I plan on making this change for my engine, but I figured I give you a heads up in case you also wanted to support an integer counter for playback. Don't know when I'll get around to it, but I'll submit a pull if you're interested.

**Comment by minecrawler** [comment]
Wouldn't a UNIX timestamp (maybe even extended so it contains ms) be exactly what you want? So instead of making an integer counter, the timestamp should just be ms since 1st Jan 1970. That would be very standard, I guess.

**Comment by OvertureGames** [comment]
It's not the integrity of the time stamp that is the issue, but rather we can't rely on getting the same delta times between Updates() during the initial run and the replay.

If you for instance try to translate an object's position moving with some velocity (v), you'd use the formula:
newPosition = currentPosition + (v * deltaTime);

If the framework using this library renders two frames each with a delta of 30ms, this will result in two state changes. Now if the replay happens to be running faster at 20ms per frame, it will instead result in three state changes instead. Even though the object has been moving for exactly the same  duration, we cannot apply the inputs at exactly the same time in the replay as the original. So if input was applied to make the object jump, it will apply the jump at some other point in time, which will result in divergence from the original play.

This is why whatever framework is using this input library needs to update its state and input at fixed frequencies. A compromise solution could be that Update() takes in the delta time in milliseconds rather than it generate it internally, as a fixed frequency update would be passing in the same delta every frame anyway.

**Comment by jkuhlmann** [comment]
Thank you for the feedback!

I get where you are coming from and I think I understand your issue. Looks to me like it would also depend on how the game treats its update - if they are based on fixed timesteps or not.

Do you agree that the easiest fix for this problem would be if one could (optionally) provide the deltatime value for InputManager::Update()?

**Comment by OvertureGames** [comment]
Yep, I believe so.

I would also suggest that the optional, supplied delta would be in milliseconds. Using floating point will work if the replay is run on the same platform/cpu it was created on, but it's possible for other platforms to calculate floats slightly different. Safest bet is to use 64bit integers.

**Comment by jkuhlmann** [comment]
I've just pushed a fix for this to the master branch (bb1ac0d27e6fdc87ffb0e5e226fe76f1889dd127). When instantiating gainput::InputManager you can now tell it to not use the system time. If you do that you then have to call gainput::InputManager::Update(uint64_t deltaTime) and supply your own delta time each frame.
