### ISSUE TITLE
MouseButtonLeft triggers KeyLeft true and keeps KeyLeft true when application looses focus

### ISSUE THREAD

**Issue by ismyhc** [jkuhlmann/gainput#13]
I have a bare bones cocos2d-x 3.9 project. I just noticed that once the running application loses focus, the GetBool() function starts to always return true. This doesn't stop when the application window comes back into focus.

Edit: Okay so heres what I see now. Left mouse actually causes the key left for keyboard input to register. So when I press left mouse button down, I actually get true for GetBool(KeyLeft). And then once the window looses focus, the GetBool(KeyLeft) stays registered as true until the application is closed.

Im using the latest version of gainput. Built on mac OS X 10.11.2.

Heres some snippets of how I'm using gainput.

```
enum Key
{
    KeyLeft
};

enum Mouse
{
    MouseLeft
};

gainput::InputManager manager;
const gainput::DeviceId keyboardId = manager.CreateDevice<gainput::InputDeviceKeyboard>();
const gainput::DeviceId mouseId = manager.CreateDevice<gainput::InputDeviceMouse>();

manager.SetDisplaySize(visibleSize.width, visibleSize.height);
map.MapBool(KeyLeft, keyboardId, gainput::KeyLeft);
map.MapBool(MouseLeft, mouseId, gainput::MouseButtonLeft);

void HelloWorld::update(float delta)
{
    manager.Update();]

// This returns true when the mouse left key is down. And then always returns true with the application looses focus
    if (map.GetBool(KeyLeft)) {
        log("LEFT");
    }

}

```

**Comment by ismyhc** [comment]
@jkuhlmann just wondering if you were able to reproduce the problems I was seeing?

Thanks!

**Comment by jkuhlmann** [comment]
Hey @ismyhc!

Looks like this might be a problem with your usage of gainput::InputMap. The map does not make a difference between user buttons for different devices. The idea being that you can map different buttons from different devices to the same "virtual" user buttons in order to reduce the work on your side.

So when you define two enums, one for keyboard keys and one mouse buttons, you basically end with only one user button (KeyLeft == MouseLeft == 0). You should put all your mapped buttons into one enum or make sure that the enum values are different in some other way.

Does that help?

**Comment by ismyhc** [comment]
@jkuhlmann Thanks for the explanation! That clears up a lot. I still see the issue that if a mapped input was used to unfocus the window, then that input bool always returns true until the window is focused again.

So if I have left mouse button mapped and I left click on another window (unfocusing my current window) then getbool for the left mouse button will always return true until I return focus to the window. Not sure if this is something that gainput could or should handle for that matter. This is something I can handle on my side, but just thought I would mention it.

Thanks again for your help. Great library! :)

-Jacob

**Comment by jkuhlmann** [comment]
I think Gainput should handle that problem. I'm going to look into it. This is on OS X, right?

**Comment by ismyhc** [comment]
@jkuhlmann Yes, latest version of OS X.

**Comment by jkuhlmann** [comment]
So I've just checked in a workaround/fix to master. Does it fix the issue for you?
