### ISSUE TITLE
Build Issues: Widnows Server 2008 R2

### ISSUE THREAD

**Issue by jlamond-work** [jkuhlmann/gainput#14]
Attempting to build gainput off of a Widnows Server 2008 R2 machine.

Build fails with the following error:

> Project "Gainput\build\Project.sln" (1) is building "Gainput\build\lib\gainput.vcxproj.metaproj" (9) on node 1 (default targets).
> Project "Gainput\build\lib\gainput.vcxproj.metaproj" (9) is building "Gainput\build\lib\gainput.vcxproj" (10) on node 1 (default targets).
> PrepareForBuild:
>   Creating directory "gainput.dir\Debug\".
> InitializeBuildStatus:
>   Creating "gainput.dir\Debug\gainput.unsuccessfulbuild" because "AlwaysCreate" was specified.
> CustomBuild:
>   Building Custom Rule gainput/lib/CMakeLists.txt
>   CMake does not need to re-run because Gainput\build\lib\CMakeFiles\generate.stamp is up-to-date.
> ClCompile:
>   C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\CL.exe /c /I"C:/Jenkins_Jobs/workspace/Gainput-Win/gainput-upstream/lib/include" /Zi /nologo /W3 /WX- /Od /Ob0 /Oy- /D WIN32 /D _WINDOWS /D _DEBUG /D GAINPUT_LIB_DYNAMIC=1 /D "CMAKE_INTDIR=\"Debug\"" /D gainput_EXPORTS /D _WINDLL /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /GR /Fo"gainput.dir\Debug\" /Fd"gainput.dir\Debug\vc100.pdb" /Gd /TP /analyze- /errorReport:queue ....\lib\source\gainput\builtin\GainputInputDeviceBuiltIn.cpp ....\lib\source\gainput\dev\GainputDev.cpp ....\lib\source\gainput\dev\GainputMemoryStream.cpp ....\lib\source\gainput\dev\GainputNetAddress.cpp ....\lib\source\gainput\dev\GainputNetConnection.cpp ....\lib\source\gainput\dev\GainputNetListener.cpp ....\lib\source\gainput\gainput.cpp ....\lib\source\gainput\GainputAllocator.cpp ....\lib\source\gainput\GainputInputDeltaState.cpp ....\lib\source\gainput\GainputInputDevice.cpp ....\lib\source\gainput\GainputInputManager.cpp ....\lib\source\gainput\GainputInputMap.cpp ....\lib\source\gainput\GainputInputState.cpp ....\lib\source\gainput\GainputMapFilters.cpp ....\lib\source\gainput\gestures\GainputButtonStickGesture.cpp ....\lib\source\gainput\gestures\GainputDoubleClickGesture.cpp ....\lib\source\gainput\gestures\GainputHoldGesture.cpp ....\lib\source\gainput\gestures\GainputPinchGesture.cpp ....\lib\source\gainput\gestures\GainputRotateGesture.cpp ....\lib\source\gainput\gestures\GainputSimultaneouslyDownGesture.cpp ....\lib\source\gainput\gestures\GainputTapGesture.cpp ....\lib\source\gainput\keyboard\GainputInputDeviceKeyboard.cpp ....\lib\source\gainput\keyboard\GainputInputDeviceKeyboardMac.cpp ....\lib\source\gainput\mouse\GainputInputDeviceMouse.cpp ....\lib\source\gainput\pad\GainputInputDevicePad.cpp ....\lib\source\gainput\pad\GainputInputDevicePadMac.cpp ....\lib\source\gainput\recorder\GainputInputPlayer.cpp ....\lib\source\gainput\recorder\GainputInputRecorder.cpp ....\lib\source\gainput\recorder\GainputInputRecording.cpp ....\lib\source\gainput\touch\GainputInputDeviceTouch.cpp
>   GainputInputDeviceBuiltIn.cpp
> ....\lib\source\gainput\builtin\GainputInputDeviceBuiltIn.cpp(118): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [Gainput\build\lib\gainput.vcxproj]
>           C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\string.h(188) : see declaration of 'strncpy'
>   GainputDev.cpp
>   GainputMemoryStream.cpp
>   GainputNetAddress.cpp
>   GainputNetConnection.cpp
>   GainputNetListener.cpp
>   gainput.cpp
>   GainputAllocator.cpp
>   GainputInputDeltaState.cpp
>   GainputInputDevice.cpp
>   GainputInputManager.cpp
>   GainputInputMap.cpp
> ....\lib\source\gainput\GainputInputMap.cpp(64): warning C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [Gainput\build\lib\gainput.vcxproj]
>           C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\string.h(105) : see declaration of 'strcpy'
>   GainputInputState.cpp
>   GainputMapFilters.cpp
>   GainputButtonStickGesture.cpp
>   GainputDoubleClickGesture.cpp
>   GainputHoldGesture.cpp
>   GainputPinchGesture.cpp
>   GainputRotateGesture.cpp
>   GainputSimultaneouslyDownGesture.cpp
>   Generating Code...
>   Compiling...
>   GainputTapGesture.cpp
>   GainputInputDeviceKeyboard.cpp
> ....\lib\source\gainput\keyboard\GainputInputDeviceKeyboard.cpp(137): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [Gainput\build\lib\gainput.vcxproj]
>           C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\string.h(188) : see declaration of 'strncpy'
>   GainputInputDeviceKeyboardMac.cpp
>   GainputInputDeviceMouse.cpp
> ....\lib\source\gainput\mouse\GainputInputDeviceMouse.cpp(121): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [Gainput\build\lib\gainput.vcxproj]
>           C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\string.h(188) : see declaration of 'strncpy'
>   GainputInputDevicePad.cpp
> ....\lib\source\gainput\pad\GainputInputDevicePad.cpp(231): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [Gainput\build\lib\gainput.vcxproj]
>           C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\string.h(188) : see declaration of 'strncpy'
>   GainputInputDevicePadMac.cpp
>   GainputInputPlayer.cpp
>   GainputInputRecorder.cpp
>   GainputInputRecording.cpp
>   GainputInputDeviceTouch.cpp
> ....\lib\source\gainput\touch\GainputInputDeviceTouch.cpp(106): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [Gainput\build\lib\gainput.vcxproj]
>           C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\string.h(188) : see declaration of 'strncpy'
>   Generating Code...
> ManifestResourceCompile:
>   C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\bin\rc.exe /nologo /fo"gainput.dir\Debug\gainput.dll.embed.manifest.res" gainput.dir\Debug\gainput_manifest.rc 
> Link:
>   C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\link.exe /ERRORREPORT:QUEUE /OUT:"Gainput\build\lib\Debug\gainput.dll" /INCREMENTAL /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib Xinput9_1_0.lib ws2_32.lib /MANIFEST /ManifestFile:"gainput.dir\Debug\gainput.dll.intermediate.manifest" /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /DEBUG /PDB:"C:/Jenkins_Jobs/workspace/Gainput-Win/gainput-upstream/build/lib/Debug/gainput.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Jenkins_Jobs/workspace/Gainput-Win/gainput-upstream/build/lib/Debug/gainput.lib" /MACHINE:X86 /DLL gainput.dir\Debug\gainput.dll.embed.manifest.res
>   gainput.dir\Debug\GainputInputDeviceBuiltIn.obj
>   gainput.dir\Debug\GainputDev.obj
>   gainput.dir\Debug\GainputMemoryStream.obj
>   gainput.dir\Debug\GainputNetAddress.obj
>   gainput.dir\Debug\GainputNetConnection.obj
>   gainput.dir\Debug\GainputNetListener.obj
>   gainput.dir\Debug\gainput.obj
>   gainput.dir\Debug\GainputAllocator.obj
>   gainput.dir\Debug\GainputInputDeltaState.obj
>   gainput.dir\Debug\GainputInputDevice.obj
>   gainput.dir\Debug\GainputInputManager.obj
>   gainput.dir\Debug\GainputInputMap.obj
>   gainput.dir\Debug\GainputInputState.obj
>   gainput.dir\Debug\GainputMapFilters.obj
>   gainput.dir\Debug\GainputButtonStickGesture.obj
>   gainput.dir\Debug\GainputDoubleClickGesture.obj
>   gainput.dir\Debug\GainputHoldGesture.obj
>   gainput.dir\Debug\GainputPinchGesture.obj
>   gainput.dir\Debug\GainputRotateGesture.obj
>   gainput.dir\Debug\GainputSimultaneouslyDownGesture.obj
>   gainput.dir\Debug\GainputTapGesture.obj
>   gainput.dir\Debug\GainputInputDeviceKeyboard.obj
>   gainput.dir\Debug\GainputInputDeviceKeyboardMac.obj
>   gainput.dir\Debug\GainputInputDeviceMouse.obj
>   gainput.dir\Debug\GainputInputDevicePad.obj
>   gainput.dir\Debug\GainputInputDevicePadMac.obj
>   gainput.dir\Debug\GainputInputPlayer.obj
>   gainput.dir\Debug\GainputInputRecorder.obj
>   gainput.dir\Debug\GainputInputRecording.obj
>   gainput.dir\Debug\GainputInputDeviceTouch.obj  /machine:X86 /debug 
> LINK : fatal error LNK1104: cannot open file 'Xinput9_1_0.lib' [gainput\build\lib\gainput.vcxproj]
> Done Building Project "Gainput\build\lib\gainput.vcxproj" (default targets) -- FAILED. 

Xinput 9.1.0 and lastest Windows SDK installed.

Xinput9_1_0.lib appears to be installed normally as part of windows 7 is this just a limitation of the platform?  is that exact version of xinput required or can it be another?

**Comment by jkuhlmann** [comment]
I think basically any version of Xinput would suffice. The issue here is that the library was changed at some point from "Xinput9_1_0" to just "xinput". As you're using a not so common Windows version, it's picking up the wrong library.

Take a look at CMakeLists.txt, there is a case for Windows where it sets XINPUT to one of the mentioned library names depending on the system version. You should be able to fix by tweaking the version comparison.

Does that help?
