### ISSUE TITLE
Undefined reference errors when using inside a DLL

### ISSUE THREAD

**Issue by calcyss** [jkuhlmann/gainput#15]
I am currently building a tiny game engine, and chose gainput for the input.
The engine gets compiled to a dll, which is then linked against and used by a little test game.
However, when i have the input system enabled (and link the dll against gainputstatic.a with `-lgainputstatic`). My library stops "working:" i get tons of undefined reference erros on the linking stage, which are not directly related to gainput, but are related to my engines internal classes and functions: 
`
C:\Windows\system32\cmd.exe /C C:/TDM-GCC-64/bin/mingw32-make.exe -j8 SHELL=cmd.exe -e -f  Makefile
"----------Building project:[ cysslib_test - Debug_win64 ]----------"
mingw32-make.exe[1]: Entering directory 'C:/Users/Daniel Wanner/Documents/Projekte/C++/cysslib/cysslib_test'
C:/TDM-GCC-64/bin/g++.exe  -c  "C:/Users/Daniel Wanner/Documents/Projekte/C++/cysslib/cysslib_test/src/MyGame.cpp" -g -pg -Wall -m64 -std=c++11 -lOpenCL  -o ./bin/Debug/win64//src_MyGame.cpp.o -I. -I../cysslib/include -I./include
C:/TDM-GCC-64/bin/g++.exe  -c  "C:/Users/Daniel Wanner/Documents/Projekte/C++/cysslib/cysslib_test/src/main.cpp" -g -pg -Wall -m64 -std=c++11 -lOpenCL  -o ./bin/Debug/win64//src_main.cpp.o -I. -I../cysslib/include -I./include
C:/TDM-GCC-64/bin/g++.exe -o ./bin/Debug/win64//cysslib_test @"cysslib_test.txt" -L. -L./bin/Debug/win64/ -L../cysslib/bin/Debug/win64/  -lcysslib  -pg -O0
./bin/Debug/win64//src_main.cpp.o: In function`main':
C:/Users/Daniel Wanner/Documents/Projekte/C++/cysslib/cysslib_test/src/main.cpp:9: undefined reference to `cyss::GameWindow::GameWindow(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int, unsigned int)'
C:/Users/Daniel Wanner/Documents/Projekte/C++/cysslib/cysslib_test/src/main.cpp:10: undefined reference to`cyss::SimpleRenderer::SimpleRenderer(unsigned int, unsigned int)'
C:/Users/Daniel Wanner/Documents/Projekte/C++/cysslib/cysslib_test/src/main.cpp:11: undefined reference to `cyss::Texture2D::Texture2D(unsigned int, unsigned int, bool)'
C:/Users/Daniel Wanner/Documents/Projekte/C++/cysslib/cysslib_test/src/main.cpp:12: undefined reference to`cyss::Texture2D::loadFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
C:/Users/Daniel Wanner/Documents/Projekte/C++/cysslib/cysslib_test/src/main.cpp:13: undefined reference to `cyss::GameWindow::show()'
C:/Users/Daniel Wanner/Documents/Projekte/C++/cysslib/cysslib_test/src/main.cpp:14: undefined reference to`cyss::GameWindow::shouldClose()'
C:/Users/Daniel Wanner/Documents/Projekte/C++/cysslib/cysslib_test/src/main.cpp:16: undefined reference to `cyss::GameWindow::update()'
C:/Users/Daniel Wanner/Documents/Projekte/C++/cysslib/cysslib_test/src/main.cpp:17: undefined reference to`cyss::GameWindow::clear()'
C:/Users/Daniel Wanner/Documents/Projekte/C++/cysslib/cysslib_test/src/main.cpp:18: undefined reference to `cyss::SimpleRenderer::reset()'
C:/Users/Daniel Wanner/Documents/Projekte/C++/cysslib/cysslib_test/src/main.cpp:20: undefined reference to`cyss::SimpleRenderer::drawTexture(cyss::Texture2D_, float, float, float, float)'
C:/Users/Daniel Wanner/Documents/Projekte/C++/cysslib/cysslib_test/src/main.cpp:22: undefined reference to `cyss::GameWindow::swapBuffers()'
C:/Users/Daniel Wanner/Documents/Projekte/C++/cysslib/cysslib_test/src/main.cpp:11: undefined reference to`cyss::Texture2D::~Texture2D()'
C:/Users/Daniel Wanner/Documents/Projekte/C++/cysslib/cysslib_test/src/main.cpp:10: undefined reference to `cyss::SimpleRenderer::~SimpleRenderer()'
C:/Users/Daniel Wanner/Documents/Projekte/C++/cysslib/cysslib_test/src/main.cpp:9: undefined reference to`cyss::GameWindow::~GameWindow()'
C:/Users/Daniel Wanner/Documents/Projekte/C++/cysslib/cysslib_test/src/main.cpp:11: undefined reference to `cyss::Texture2D::~Texture2D()'
C:/Users/Daniel Wanner/Documents/Projekte/C++/cysslib/cysslib_test/src/main.cpp:10: undefined reference to`cyss::SimpleRenderer::~SimpleRenderer()'
C:/Users/Daniel Wanner/Documents/Projekte/C++/cysslib/cysslib_test/src/main.cpp:9: undefined reference to `cyss::GameWindow::~GameWindow()'
collect2.exe: error: ld returned 1 exit status
mingw32-make.exe[1]: *_\* [bin/Debug/win64//cysslib_test] Error 1
cysslib_test.mk:78: recipe for target 'bin/Debug/win64//cysslib_test' failed
mingw32-make.exe[1]: Leaving directory 'C:/Users/Daniel Wanner/Documents/Projekte/C++/cysslib/cysslib_test'
mingw32-make.exe: **\* [All] Error 2
Makefile:4: recipe for target 'All' failed
====18 errors, 0 warnings====
`

These undefined reference errors dont occur when not enabling the input system, and thus not linking against gainput.

**Comment by calcyss** [comment]
Seems the formatting got a little f****ed up. Sorry about that.

**Comment by jkuhlmann** [comment]
Have you by any chance been able to fix this? As far as I can tell, the errors are not really related to Gainput directly, but your code instead? I could imagine the static library causing problems when linked into a dynamic one and then used from somewhere else, but what you're seeing would be an interesting result of that.
If you're already using dynamic libraries, could you maybe also use Gainput in the form of a dynamic library?
