### ISSUE TITLE
Is the project still in active development?

### ISSUE THREAD

**Issue by eliaskosunen** [jkuhlmann/gainput#19]
I am worried, because this seems like such an awesome library, but the last commit has been made in February.

**Comment by jkuhlmann** [comment]
You're right, it has been some time since the last commit and I mean to be getting back to this project, but have been busy with other things recently. Be assured that I'm still committed to the project and am also using it in professional project so if there are any issues let me know!

**Comment by eliaskosunen** [comment]
It's great that you're still working on this!
