### ISSUE TITLE
Input not working on OS X

### ISSUE THREAD

**Issue by CairnThePerson** [jkuhlmann/gainput#25]
On version 10.11.2 of OS X, I’m trying to get the library to run. I don’t have any build errors, but to be sure, I’ll explain my process. I’ve done what is said on [this page](http://gainput.johanneskuhlmann.de/api/page_building.html) and that works. I’ve got a small C++ file to test if it works.

```
#include <gainput/gainput.h>

enum Button
{
    ButtonConfirm
};

int main() {
    gainput::InputManager manager;
    manager.SetDisplaySize(50, 50);
    const gainput::DeviceId keyboardId = manager.CreateDevice<gainput::InputDeviceKeyboard>();
    const gainput::DeviceId mouseId = manager.CreateDevice<gainput::InputDeviceMouse>();
    const gainput::DeviceId padId = manager.CreateDevice<gainput::InputDevicePad>();
    const gainput::DeviceId touchId = manager.CreateDevice<gainput::InputDeviceTouch>();
    
    gainput::InputMap map(manager);
    map.MapBool(ButtonConfirm, keyboardId, gainput::KeyReturn);
    map.MapBool(ButtonConfirm, mouseId, gainput::MouseButtonLeft);
    map.MapBool(ButtonConfirm, padId, gainput::PadButtonA);
    map.MapBool(ButtonConfirm, touchId, gainput::Touch0Down);
    
    bool running = true;
    
    while (running)
    {
        manager.Update();
        
        // May need some platform-specific message handling here
        
        if (map.GetBoolWasDown(ButtonConfirm))
        {
            running = false;
        }
    }
    return 0;
}
```

It’s essentially just a modified version of the code on the front page of this github project. If the code isn’t correct, I’d be surprised, but I’m not getting any errors. I’m building like this

`g++ main.cpp -o main -I/usr/local/include -L/usr/local/lib -lgainput`

Again, no build errors. When I run it, it pops up a terminal window. From that terminal window, it seems like it’s running, but pressing enter or left clicking doesn’t close the program like the code I have would seem to do.

I've tried running the sample programs, but they do a similar thing - open the terminal window and proceed to not do what their code seems to imply they would. No windows pop up or anything.

edit: If I'm building wrong somehow, could you go into a little detail about how you build for OS X?

**Comment by jkuhlmann** [comment]
Hi,

unfortunately, the sample code on the front page is a bit too simplistic to actually be able to register any input on its own. You need a proper UI window which allows Gainput to receive input.

You can look at the "basic" sample to see he barebones version of how this can work:
https://github.com/jkuhlmann/gainput/blob/master/samples/basic/basicsample_mac.mm

Does that help?
