### ISSUE TITLE
macOS build error

### ISSUE THREAD

**Issue by MrCapone** [jkuhlmann/gainput#26]
I have added gainput as git submodule, and my project build fails on
```
gainput/lib/source/gainput/mouse/GainputInputDeviceMouseMac.mm:110:27: error: no matching function for call to 'CGEventTapCreate'
        CFMachPortRef eventTap = CGEventTapCreate(kCGSessionEventTap,
```

Build fails on cmake and on generated Xcode project

**Comment by jkuhlmann** [comment]
Weird that it compiled for me and on Travis CI. Anyway, your fix is merged. Thanks!
