### ISSUE TITLE
Error in compilation for android

### ISSUE THREAD

**Issue by vinod-mv** [jkuhlmann/gainput#31]
Hi,
     When trying to compile the source for android using instructions in the Readme, I encountered the following error:

"/lib/source/gainput/touch/GainputInputDeviceTouch.cpp:32:6: error: 'variant' was not declared in this scope"

I got it compiled by changing the line:

InputDeviceTouch::InputDeviceTouch(InputManager& manager, DeviceId device, unsigned index, DeviceVariant /*variant*/) :

to:

InputDeviceTouch::InputDeviceTouch(InputManager& manager, DeviceId device, unsigned index, DeviceVariant variant) :

Am I right to uncomment variant?

**Comment by MrCapone** [comment]
Yes, this variable must be uncomment for iOS and android. You can create pull request with this fix.

**Comment by jkuhlmann** [comment]
Sorry, it's fixed on the master branch now.
