### ISSUE TITLE
gainputstatic has unresolved external symbols

### ISSUE THREAD

**Issue by minecrawler** [jkuhlmann/gainput#6]
building is no problem, but when it comes to using the `.lib`...

	1>gainputstatic.lib(GainputInputDevicePad.obj) : error LNK2001: unresolved external symbol XInputGetState
	1>gainputstatic.lib(GainputInputDevicePad.obj) : error LNK2001: unresolved external symbol XInputSetState
	1>gainputstatic.lib(GainputInputRecording.obj) : error LNK2001: unresolved external symbol __imp_htonl
	1>gainputstatic.lib(GainputInputRecording.obj) : error LNK2001: unresolved external symbol __imp_ntohl

**Comment by jkuhlmann** [comment]
Can you try linking your executable against xinput?

**Comment by minecrawler** [comment]
xinput.lib and Ws2_32.lib. Thank you, brought me on the correct path :)
