### ISSUE TITLE
Program crashes when using InputManager

### ISSUE THREAD

**Issue by Zandare** [jkuhlmann/gainput#7]
I have built and linked gainput.
As soon as I add line: 
gainput::InputManager input;

I get no warnings/errors, but program crashed right after start. Even a minimal example crashed.

Any ideas would be appreciated!

EDIT: I am using msvc 2013 64 bit

**Comment by jkuhlmann** [comment]
Could you post a call stack and check if there is possibly anything interesting in the log output?

**Comment by Zandare** [comment]
Hi! I wanted to give gainput another try and downloaded your recent version from github. Sorry I can't reproduce my issue from above. Instead I recompiled with cmake and visual studio 2013 x64 (Release. static) with no issues. Now when I init InputManager I get the following errors:
gainputstatic.lib(GainputInputDevicePad.obj):-1: error: LNK2019: Verweis auf nicht aufgelöstes externes Symbol "XInputGetState" in Funktion ""public: virtual void __cdecl gainput::InputDevicePadImplWin::Update(class gainput::InputDeltaState *)" (?Update@InputDevicePadImplWin@gainput@@UEAAXPEAVInputDeltaState@2@@Z)".
gainputstatic.lib(GainputInputDevicePad.obj):-1: error: LNK2019: Verweis auf nicht aufgelöstes externes Symbol "XInputSetState" in Funktion ""public: virtual bool __cdecl gainput::InputDevicePadImplWin::Vibrate(float,float)" (?Vibrate@InputDevicePadImplWin@gainput@@UEAA_NMM@Z)".
gainputstatic.lib(GainputInputRecording.obj):-1: error: LNK2019: Verweis auf nicht aufgelöstes externes Symbol "__imp_htonl" in Funktion ""public: unsigned __int64 __cdecl gainput::Stream::Write<unsigned int>(unsigned int const &)" (??$Write@I@Stream@gainput@@QEAA_KAEBI@Z)".
gainputstatic.lib(GainputInputRecording.obj):-1: error: LNK2019: Verweis auf nicht aufgelöstes externes Symbol "__imp_ntohl" in Funktion ""public: unsigned __int64 __cdecl gainput::Stream::Read<unsigned int>(unsigned int &)" (??$Read@I@Stream@gainput@@QEAA_KAEAI@Z)".

Is something missing in the library or am I missing something? Thank you in advance.

**Comment by minecrawler** [comment]
Well,
1) Please translate all error messages to English
2) First search all other issues; I had the same problem at some point and the issue is already resolved
3) **You need to include `xinput.lib` and `Ws2_32.lib`** 

See Issue https://github.com/jkuhlmann/gainput/issues/6

**Comment by Zandare** [comment]
Ok I installed DirectX SDK and linked xinput.lib and cut my errors in half:

gainputstatic.lib(GainputInputRecording.obj):-1: error: LNK2019: Reference to not found external symbol "__imp_htonl" in Funktion ""public: unsigned __int64 __cdecl gainput::Stream::Write<unsigned int>(unsigned int const &)" (??$Write@I@Stream@gainput@@QEAA_KAEBI@Z)".
gainputstatic.lib(GainputInputRecording.obj):-1: error: LNK2019: Reference to not found external symbol "__imp_ntohl" in Funktion ""public: unsigned __int64 __cdecl gainput::Stream::Read<unsigned int>(unsigned int &)" (??$Read@I@Stream@gainput@@QEAA_KAEAI@Z)".

I am compiling the program in 64bit. Linking to WS2_32.lib brought up tons of erros. I linked to this path: C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\lib.
It seems to cause conflicts with other libraries I use...
