### ISSUE TITLE
Is a Joystick supported?

### ISSUE THREAD

**Issue by Zandare** [jkuhlmann/gainput#9]
So, I've properly set up gainput into my Qt project, at least mouse and keyboard inputs are recognized by gainput. Now I am trying to bring my joystick to life but without success so far. Now I am wondering, is it even supported in your library? Is a joystick considered a gamepad? :D 
Your PadButtons enumerations start with 17, though I know my joystick buttons range from 0 - 11. Thanks in advance!

**Comment by Zandare** [comment]
I am still interested in my question, though I want to notice that I solved my problem by binding a part of another library in my project. I integrated <SFML\Window\Joystick.hpp> that only uses these static functions to work without initialization:

// Is joystick #0 connected?
bool connected = sf::Joystick::isConnected(0);
// How many buttons does joystick #0 support?
unsigned int buttons = sf::Joystick::getButtonCount(0);
// Does joystick #0 define a X axis?
bool hasX = sf::Joystick::hasAxis(0, sf::Joystick::X);
// Is button #2 pressed on joystick #0?
bool pressed = sf::Joystick::isButtonPressed(0, 2);
// What's the current position of the Y axis on joystick #0?
float position = sf::Joystick::getAxisPosition(0, sf::Joystick::Y);

I don't want to be ungrateful. I am sure your library is on a good way. This may be interesting for other users who are looking for input libraries.

**Comment by jkuhlmann** [comment]
Sorry for the slow response time. I hope you are still interested in some insight into this.

I guess you are on Windows?

Conceptually, joysticks are considered gamepads. They should work on most platforms. On Windows, however, Gainput currently only uses XINPUT for acquiring gamepad data. XINPUT is Microsoft's only current library for this and it only really supports Xbox gamepads. So, as long as your joystick does not show up as an Xbox gamepad, you are out of luck for now.

I'm getting the impression that it might make sense to add support for the deprecated DirectInput API or maybe the joystick API.

**Comment by Zandare** [comment]
Thx got it! Yes, this would extend your library nicely. It is hard to find a lightweight, easy, purely HID oriented library without all the graphics, sound modules etc.!

**Comment by sytelus** [comment]
I'm also very interested in using gainput for [AIrSim ](https://github.com/microsoft/airsim) project. We basically connect remote controls used for drones to PC via USB. They show up as joystick and we want to access this input. I just tried out gainput to access this and as mentioned in this thread, it doesn't recognize joysticks at all.

I think current way to do this is using Raw Input APIs (instead of DirectInput APIs). There just doesn't seem to be good cross platform library that allows access to joysticks without lot of fuss. It would be very nice to have this capability in gainput!

**Comment by kerm1t** [comment]
Hi, just tried to read USB Joypad input with current sources (3/2/2019) but no response in Gainput test projects.
